export const PUB_SUB_EVENTS = {
	MESSAGE: {
		ADDED: 'MESSAGE:ADDED',
	},
	USER: {
		ADDED: 'USER:ADDED',
	},
	ACCOUNT: {
		ADDED: 'ACCOUNT:ADDED',
	},
	TRANSACTION: {
		ADDED: 'TRANSACTION:ADDED',
	},
} as const;
